- name: Update package cache
  dnf: update_cache=yes

- name: Upgrade dnf package
  dnf: name=dnf state=latest

- name: Install dnf packages
  dnf:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ packages }}"

- name: Remove dnf packages
  dnf:
    name: "{{ item }}"
    update_cache: yes
    state: absent
  loop: "{{ remove_packages }}"
