- name: Install git
  dnf: name=git state=present

- name: Create gitconfig
  template:
    src: "gitconfig.j2"
    dest: "{{dotfiles_user_home}}/.gitconfig"

- name: Install tig
  dnf: name=tig state=present
