- name: Install Terminator
  dnf: name=terminator state=present

- name: Ensure destination directory exists
  file:
    path: "{{ dotfiles_user_home }}/.config/terminator"
    state: directory
    mode: "0755"

- name: Symlink config
  file:
    src: "{{ dotfiles_home }}/roles/terminator/files/config"
    dest: "{{dotfiles_user_home}}/.config/terminator/config"
    state: link
